language: java
jdk: openjdk8
install: true

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage : build
      script: ./mvnw clean install

    - stage : publish
      if: branch = master
      script: ./mvnw pact:publish